name: Dastardly Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dastardly scan
        run: |
          docker run --rm -v ${{ github.workspace }}:/zap/wrk:rw -e BURP_START_URL=https://prosect.com.br -e BURP_REPORT_FILE_PATH=/zap/wrk/dastardly_scan_report.xml -t public.ecr.aws/portswigger/dastardly:latest

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-scan-results
          path: dastardly_scan_report.xml
